### ISSUE TITLE
Question: Support For Multiple Screens?

### ISSUE THREAD

**Issue by mitchellsayer** [pupil-labs/real-time-screen-gaze#2]
This is not an issue with the software but rather a request for input from the maintainers regarding a specific use case.

I am looking to use this library with the Neon glasses to infer real-time gaze location for desktop setups with up to 3 monitors. I would like to know if this behavior is something that this library could support and what limitations or other considerations could have an impact on multi screen performance.

If this behavior is not supported, would it be possible for me to extend the package to support it and if this is the case, is there any guidance you can provide as I explore this route?

**Comment by domstoppable** [comment]
This should already be supported (although not really tested AFAIK). Just configure a separate surface for each display, each with unique AprilTag markers

**Comment by mitchellsayer** [comment]
@domstoppable OK great, I'll test it out and create a specific issue if I run into any odd behavior.
